image:
  repository: image-registry.openshift-image-registry.svc:5000/build/gitops-demo-msr
  tag: 1.0.5
podSecurityContext:
  fsGroup: null

imagePullSecrets:

ingress:
  enabled: false
 
route:
  enabled: true
  host: gitops-demo-msr.dev.apps-crc.testing
  tls:
    termination: edge