image:
  repository: image-registry.openshift-image-registry.svc:5000/build/msr-base
  tag: latest
podSecurityContext:
  fsGroup: null

imagePullSecrets:

ingress:
  enabled: false
 
route:
  enabled: true
  host: gitops-demo-msr.dev.apps-crc.testing
  tls:
    termination: edge