apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-prod
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo-prod
  project: default
  sources:
  - path: microservicesruntime/helm
    helm:
      valueFiles:
      - $values/deploy/prod/values.yaml
      - $license/values.yaml
    repoURL: 'https://github.com/SoftwareAG/webmethods-helm-charts.git'
    targetRevision: 'dev-openshift'
  - ref: values
    repoURL: 'https://github.com/MarcFriedhoff/gitops-demo-container.git'
    targetRevision: 'prod'
  - ref: license
    repoURL: 'https://github.com/MarcFriedhoff/gitops-demo-license.git'
    targetRevision: 'HEAD'
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true